Test GitHub actions
cuenca-mx/cuenca-java pull request #5
Opened 2022-02-08 23:07 UTC by mike-one

closes #4 

Se agrega la configuración para correr los test automáticamente cada que se haga push de todas las ramas.

2022-02-09 17:14 UTC, alexviquez requested changes
unos comments

2022-02-09 17:14 UTC, alexviquez commented on .github/workflows/maven.yml
> +name: Java CI with Maven
cambia el nombre a especificar que hacae el github action, también el nombre del archivo por ejemplo:
name: Build test with maven
test.yml

2022-02-09 17:14 UTC, alexviquez commented on .github/workflows/maven.yml
> +        run: mvn -B test
crea una matriz de pruebas paraa aque puedas probar con diferentes JDK, desde la versión 10 a la versión 15 si es posible

2022-02-09 17:14 UTC, alexviquez commented on .github/workflows/maven.yml
> +        run: mvn -B test
Revisa com hacemos en python para probar en 3.7, 3.8, 3.9

2022-02-09 22:07 UTC, mike-one commented on .github/workflows/maven.yml
> +        run: mvn -B test
Están disponibles las versiones 11, 16 y 17

2022-02-09 22:17 UTC, alexviquez requested changes
revisar versiones de java

2022-02-09 22:17 UTC, alexviquez commented on .github/workflows/test.yml
> +        java-version: ['11', '16', '17']
porque solo estas versiones ? y la 8? parece que todavía tiene soporte
https://en.wikipedia.org/wiki/Java_version_history

2022-02-16 21:11 UTC, alexviquez requested changes
unos comments

2022-02-16 21:11 UTC, alexviquez commented on pom.xml
> +            <organizationUrl>http://github.com/cuenca-mx/</organizationUrl>
usamos Cuenca Devs
dev@cuenca.com

2022-02-16 21:11 UTC, alexviquez commented on .github/workflows/publish_to_maven_central.yml
> +    branches: [ main ]
jhay que cambiar esto, solo liberamos en release y cuando hay un tag, checa otros repos

2022-02-16 21:11 UTC, alexviquez commented on .github/workflows/publish_to_maven_central.yml
> +    if: "contains(github.event.head_commit.message, 'PUBLISH')"
revisa como lo hacemos en otros proyectos

2022-02-17 16:19 UTC, alexviquez requested changes
un comment

2022-02-17 16:19 UTC, alexviquez commented on pom.xml
>              <name>Miguel Acosta</name>
cuenca devs
https://github.com/cuenca-mx/cuenca-dart/blob/main/pubspec.yaml#L4

2022-02-17 18:12 UTC, alexviquez approved these changes

2022-02-17 18:12 UTC, merged